import tkinter as tk
cal=tk.Tk()
#cal.iconbitmap("C:/Users/ELCOT/AppData/Local/Programs/Python/Python38-32")
cal.title("CALCULTOR")
def click(number):
        global op
        op=op+str(number)
        #print(op)
        variable.set(op)
def clear():
        global op
        op=""
        variable.set(op)
def sum():
        global op
        op=str(eval(op))
        variable.set(op)
op=""
b1=tk.Button(cal,text='1',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(1))
b1.grid(row=3,column=0)
b2=tk.Button(cal,text='2',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(2))
b2.grid(row=3,column=1)
b3=tk.Button(cal,text='3',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(3))
b3.grid(row=3,column=2)
b0=tk.Button(cal,text='0',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(0))
b0.grid(row=4,column=0)
bpoint=tk.Button(cal,text='.',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click("."))
bpoint.grid(row=4,column=1)
bclear=tk.Button(cal,text='C',font=("arial",20,"bold"),bd=5,padx=10,command= clear)
bclear.grid(row=4,column=2)
bclear.config(bg="Blue")
bpl=tk.Button(cal,text='+',font=("arial",20,"bold"),bd=7,bg="green",padx=10,command= lambda : click("+"))
bpl.grid(row=1,column=4)
bmi=tk.Button(cal,text='-',font=("arial",20,"bold"),bd=7,bg="green",padx=10,command= lambda : click("-"))
bmi.grid(row=2,column=4)
bmu=tk.Button(cal,text='*',font=("arial",20,"bold"),bd=7,bg="green",padx=10,command= lambda : click("*"))
bmu.grid(row=3,column=4)
bdi=tk.Button(cal,text='/',font=("arial",20,"bold"),bd=7,bg="green",padx=10,command= lambda : click("/"))
bdi.grid(row=4,column=4)
beq=tk.Button(cal,text='=',font=("arial",20,"bold"),bd=10,bg=("Red"),padx=140,command= sum)
beq.grid(row=5,columnspan=5)
variable=tk.StringVar()
disp=tk.Entry(cal,font=("arial",20,"bold"),bd=25,textvariable=variable,justify="right")
disp.grid(columnspan=5)
b4=tk.Button(cal,text='4',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(4))
b4.grid(row=2,column=0)
b5=tk.Button(cal,text='5',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(5))
b5.grid(row=2,column=1)
b6=tk.Button(cal,text='6',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(6))
b6.grid(row=2,column=2)
b7=tk.Button(cal,text='7',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(7))
b7.grid(row=1,column=0)
b8=tk.Button(cal,text='8',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(8))
b8.grid(row=1,column=1)
b9=tk.Button(cal,text='9',font=("arial",20,"bold"),bd=5,padx=10,command= lambda : click(9))
b9.grid(row=1,column=2)
cal.mainloop()
